# How to use this file:
# docker-compose up -d

version: '2'
services:
  bughouse:
    image: daptiv/node
    container_name: bughouse
    volumes:
      - $PWD:/bughouse
    working_dir: /bughouse
    ports:
      - "3000:3000"
    environment:
      - TP_CREDENTIALS
    restart: always
    command: |
      bash -c 'bash -s <<EOF
      yarn install
      npm start
      EOF'
